### ISSUE TITLE
Safe prime size is occasionally off by a few bits

### ISSUE THREAD

**Issue by robinhundt** [mikelodder7/glass_pumpkin#12] opened 2021-09-27 20:10 UTC
When generating safe primes with a specific size via [safe_prime::new](https://docs.rs/glass_pumpkin/1.1.0/glass_pumpkin/safe_prime/fn.new.html), the resulting Integer sometimes has a size which is off by one or two bits. 

Related: https://github.com/mikelodder7/unknown_order/issues/4

**Comment by mikelodder7** [comment] 2021-09-27 20:25
I see. I'll investigate to see what is the cause.

**Comment by STashakkori** [comment] 2021-09-28 03:52
Yea I'm a bit confused on this myself. Is a parameter of 128 supposed to result in a 128-digit output?
Because currently an input of 128 gives a 39 digit output

**Comment by STashakkori** [comment] 2021-09-28 06:58
If you set it to generate a prime of length 128 bits, it generates a number with 39 digits approximately 3/4 of the time and a number with 38 digits 1/4 of the time.

**Comment by mikelodder7** [comment] 2021-09-28 14:01
Fixed in bce0b60ae0ac60caa1cd74aaeb7c4f84739e6f1d

**Closed as completed by mikelodder7** 2021-09-28 14:01 UTC
